-- DECIDE v1.5 PostgreSQL skeleton, NOT a complete migration/RPC implementation.
-- Supabase supplies anon/authenticated/service_role. Standalone QA creates these roles.
BEGIN;
CREATE SCHEMA app_private;
REVOKE ALL ON SCHEMA app_private FROM PUBLIC,anon,authenticated;
CREATE TABLE app_private.actors (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),auth_user_id uuid NOT NULL UNIQUE,
 kind text NOT NULL CHECK(kind IN ('guest','account')),status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','suspended','deleting','deleted')),
 registered_at timestamptz,terms_version text,beta_age_confirmed_at timestamptz,anonymous_disabled_until timestamptz,
 merged_into uuid REFERENCES app_private.actors(id),created_at timestamptz NOT NULL DEFAULT now(),
 CHECK(merged_into IS NULL OR merged_into<>id),CHECK(kind<>'account' OR registered_at IS NOT NULL));
-- Actual Supabase migration MUST add auth_user_id FK to auth.users(id); omitted for portable SQL QA only.
CREATE TABLE app_private.profiles (
 actor_id uuid PRIMARY KEY REFERENCES app_private.actors(id) ON DELETE CASCADE,
 handle text NOT NULL UNIQUE CHECK(handle ~ '^[a-z0-9_]{3,20}$'),display_name text NOT NULL CHECK(length(btrim(display_name))>0 AND octet_length(display_name)<=4096),
 bio text NOT NULL DEFAULT '' CHECK(octet_length(bio)<=16384),avatar_asset_id uuid,
 profile_theme text NOT NULL DEFAULT 'lilac' CHECK(profile_theme IN ('lilac','lime','neutral')),
 sixteen_type text CHECK(sixteen_type ~ '^[EI][NS][TF][JP]$'),show_sixteen_type boolean NOT NULL DEFAULT false,
 show_dna boolean NOT NULL DEFAULT false,show_friend_count boolean NOT NULL DEFAULT false,show_follow_count boolean NOT NULL DEFAULT false,
 handle_changed_at timestamptz,revision integer NOT NULL DEFAULT 1 CHECK(revision>0),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app_private.handle_reservations(handle text PRIMARY KEY,former_actor_id uuid REFERENCES app_private.actors(id) ON DELETE SET NULL,reserved_until timestamptz NOT NULL);
CREATE TABLE app_private.friendships(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),actor_low uuid NOT NULL REFERENCES app_private.actors(id) ON DELETE CASCADE,actor_high uuid NOT NULL REFERENCES app_private.actors(id) ON DELETE CASCADE,requester_id uuid NOT NULL REFERENCES app_private.actors(id) ON DELETE CASCADE,status text NOT NULL CHECK(status IN ('pending','accepted','rejected')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(actor_low,actor_high),CHECK(actor_low<actor_high),CHECK(requester_id IN (actor_low,actor_high)));
CREATE TABLE app_private.follows(follower_id uuid REFERENCES app_private.actors(id) ON DELETE CASCADE,followee_id uuid REFERENCES app_private.actors(id) ON DELETE CASCADE,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(follower_id,followee_id),CHECK(follower_id<>followee_id));
CREATE TABLE app_private.blocks(blocker_id uuid REFERENCES app_private.actors(id) ON DELETE CASCADE,blocked_id uuid REFERENCES app_private.actors(id) ON DELETE CASCADE,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(blocker_id,blocked_id),CHECK(blocker_id<>blocked_id));
CREATE TABLE app_private.posts (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),author_id uuid NOT NULL REFERENCES app_private.actors(id) ON DELETE CASCADE,
 intent text NOT NULL DEFAULT 'decision' CHECK(intent IN ('decision','poll')),question text NOT NULL CHECK(length(btrim(question))>0 AND octet_length(question)<=16384),context text NOT NULL DEFAULT '' CHECK(octet_length(context)<=16384),
 category_id text NOT NULL DEFAULT 'other' CHECK(category_id IN ('romance','relationships','fashion_beauty','food','shopping','travel','school_work','hobbies','money','politics_society','other')),
 category_source text NOT NULL DEFAULT 'fallback' CHECK(category_source IN ('ai','author','fallback')),ai_tags jsonb NOT NULL DEFAULT '[]',
 audience text NOT NULL DEFAULT 'friends_link' CHECK(audience IN ('friends','friends_link','public')),audience_mode text NOT NULL DEFAULT 'all' CHECK(audience_mode IN ('all','selected')),
 vote_mode text NOT NULL DEFAULT 'named' CHECK(vote_mode IN ('named','choice_anonymous','participation_hidden')),is_anonymous boolean NOT NULL DEFAULT false,
 publication text NOT NULL DEFAULT 'checking' CHECK(publication IN ('checking','visible','held','rejected','deleted')),poll_state text NOT NULL DEFAULT 'open' CHECK(poll_state IN ('open','closed')),
 duration_preset text NOT NULL DEFAULT '3h' CHECK(duration_preset IN ('15m','1h','3h','1d','1w','custom')),published_at timestamptz,ends_at timestamptz,extension_used boolean NOT NULL DEFAULT false,
 deadline_version integer NOT NULL DEFAULT 1,actual_closed_at timestamptz,close_reason text CHECK(close_reason IN ('deadline','manual','no_answers')),
 final_preset text DEFAULT 'next_day' CHECK(final_preset IN ('immediate','same_day','next_day','3d','1w','custom')),fixed_final_due_at timestamptz,final_due_at timestamptz,final_revision integer,deferred_until timestamptz,
 timezone text NOT NULL DEFAULT 'Asia/Tokyo',first_vote_ever_at timestamptz,public_guest_allowed boolean NOT NULL DEFAULT false,allow_repost boolean NOT NULL DEFAULT true,allow_remix boolean NOT NULL DEFAULT false,reaction_notified_at timestamptz,
 revision integer NOT NULL DEFAULT 1 CHECK(revision>0),content_revision integer NOT NULL DEFAULT 1,policy_revision integer NOT NULL DEFAULT 1,aggregate_revision integer NOT NULL DEFAULT 1,
 deleted_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),
 CHECK(audience<>'public' OR vote_mode='participation_hidden'),CHECK(audience_mode<>'selected' OR audience='friends'),
 CHECK(NOT is_anonymous OR (audience='friends' AND audience_mode='all' AND intent='decision')),
 CHECK(intent<>'poll' OR (audience='public' AND final_preset IS NULL AND final_due_at IS NULL AND final_revision IS NULL)),
 CHECK((poll_state='closed')=(actual_closed_at IS NOT NULL)),CHECK(publication<>'visible' OR (published_at IS NOT NULL AND ends_at IS NOT NULL)),CHECK(ends_at IS NULL OR published_at IS NULL OR ends_at>=published_at));
CREATE TABLE app_private.audience_members(post_id uuid REFERENCES app_private.posts(id) ON DELETE CASCADE,actor_id uuid REFERENCES app_private.actors(id) ON DELETE CASCADE,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(post_id,actor_id));
CREATE TABLE app_private.anonymous_usage(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),author_id uuid NOT NULL REFERENCES app_private.actors(id) ON DELETE CASCADE,created_at timestamptz NOT NULL DEFAULT now());
-- Anonymous usage intentionally has no post FK: source deletion cannot reset the rolling 168h limit.
CREATE TABLE app_private.assets(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),owner_id uuid NOT NULL REFERENCES app_private.actors(id) ON DELETE CASCADE,post_id uuid REFERENCES app_private.posts(id) ON DELETE CASCADE,
 slot text NOT NULL CHECK(slot IN ('A','B','outcome','avatar')),status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','processing','ready','rejected','superseded','deleted')),
 original_key text NOT NULL UNIQUE,normalized_key text,thumbnail_key text,mime_type text NOT NULL CHECK(mime_type IN ('image/jpeg','image/png','image/webp')),size_bytes bigint NOT NULL CHECK(size_bytes>0 AND size_bytes<=10485760),width integer CHECK(width>0),height integer CHECK(height>0),source_version integer NOT NULL DEFAULT 1,sha256 text,created_at timestamptz NOT NULL DEFAULT now(),CHECK(width IS NULL OR height IS NULL OR width::bigint*height<=24000000));
CREATE UNIQUE INDEX assets_active_slot ON app_private.assets(post_id,slot) WHERE post_id IS NOT NULL AND status NOT IN ('deleted','superseded','rejected');
ALTER TABLE app_private.profiles ADD FOREIGN KEY(avatar_asset_id) REFERENCES app_private.assets(id) ON DELETE SET NULL;
CREATE TABLE app_private.post_options(post_id uuid REFERENCES app_private.posts(id) ON DELETE CASCADE,choice text CHECK(choice IN ('A','B')),label text NOT NULL CHECK(length(btrim(label))>0 AND octet_length(label)<=16384),asset_id uuid REFERENCES app_private.assets(id) ON DELETE SET NULL,crop_x numeric NOT NULL DEFAULT 0.5 CHECK(crop_x BETWEEN 0 AND 1),crop_y numeric NOT NULL DEFAULT 0.5 CHECK(crop_y BETWEEN 0 AND 1),PRIMARY KEY(post_id,choice));
CREATE FUNCTION app_private.require_two_options() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,app_private AS $$
DECLARE target_id uuid; BEGIN
 IF TG_TABLE_NAME='posts' THEN target_id:=NEW.id; ELSIF TG_OP='DELETE' THEN target_id:=OLD.post_id; ELSE target_id:=NEW.post_id; END IF;
 IF EXISTS(SELECT 1 FROM app_private.posts WHERE id=target_id) AND (SELECT count(*) FROM app_private.post_options WHERE post_id=target_id)<>2 THEN RAISE EXCEPTION 'A post requires exactly A and B options' USING ERRCODE='23514'; END IF;RETURN NULL; END $$;
CREATE CONSTRAINT TRIGGER post_requires_two AFTER INSERT OR UPDATE ON app_private.posts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app_private.require_two_options();
CREATE CONSTRAINT TRIGGER options_require_two AFTER INSERT OR UPDATE OR DELETE ON app_private.post_options DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app_private.require_two_options();
CREATE TABLE app_private.addenda(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),post_id uuid NOT NULL REFERENCES app_private.posts(id) ON DELETE CASCADE,text text NOT NULL CHECK(octet_length(text)<=16384),moderation text NOT NULL DEFAULT 'checking' CHECK(moderation IN ('checking','visible','held','rejected','deleted')),created_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz);
CREATE TABLE app_private.ballots(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),post_id uuid NOT NULL REFERENCES app_private.posts(id) ON DELETE CASCADE,actor_id uuid NOT NULL REFERENCES app_private.actors(id) ON DELETE CASCADE,choice text NOT NULL CHECK(choice IN ('A','B')),origin_kind text NOT NULL CHECK(origin_kind IN ('account','guest')),first_accepted_at timestamptz NOT NULL DEFAULT now(),change_count integer NOT NULL DEFAULT 0 CHECK(change_count BETWEEN 0 AND 1),locked_at timestamptz,validity text NOT NULL DEFAULT 'valid' CHECK(validity IN ('valid','invalid','merged')),invalid_reason text,revision integer NOT NULL DEFAULT 1,FOREIGN KEY(post_id,choice) REFERENCES app_private.post_options(post_id,choice),CHECK(change_count=0 OR locked_at IS NOT NULL),CHECK(locked_at IS NULL OR locked_at>=first_accepted_at));
CREATE UNIQUE INDEX one_valid_ballot ON app_private.ballots(post_id,actor_id) WHERE validity='valid';
CREATE FUNCTION app_private.protect_frozen_post() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,app_private AS $$ BEGIN
 IF NEW.author_id IS DISTINCT FROM OLD.author_id THEN RAISE EXCEPTION 'Author is immutable' USING ERRCODE='23514'; END IF;
 IF OLD.first_vote_ever_at IS NOT NULL OR OLD.poll_state='closed' THEN
 IF ROW(NEW.first_vote_ever_at,NEW.question,NEW.context,NEW.intent,NEW.vote_mode,NEW.is_anonymous) IS DISTINCT FROM ROW(OLD.first_vote_ever_at,OLD.question,OLD.context,OLD.intent,OLD.vote_mode,OLD.is_anonymous) THEN RAISE EXCEPTION 'Source content is frozen' USING ERRCODE='23514'; END IF;
 IF (OLD.audience='friends' AND NEW.audience<>'friends') OR (OLD.audience='friends_link' AND NEW.audience='public') THEN RAISE EXCEPTION 'Audience cannot expand' USING ERRCODE='23514'; END IF;END IF;RETURN NEW;END $$;
CREATE TRIGGER protect_frozen_post BEFORE UPDATE ON app_private.posts FOR EACH ROW EXECUTE FUNCTION app_private.protect_frozen_post();
CREATE FUNCTION app_private.protect_frozen_option() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,app_private AS $$ DECLARE target_id uuid;BEGIN
 IF TG_OP='UPDATE' AND (NEW.post_id IS DISTINCT FROM OLD.post_id OR NEW.choice IS DISTINCT FROM OLD.choice) THEN RAISE EXCEPTION 'Option identity is immutable' USING ERRCODE='23514';END IF;
 IF TG_OP='INSERT' THEN target_id:=NEW.post_id;ELSE target_id:=OLD.post_id;END IF;
 IF EXISTS(SELECT 1 FROM app_private.posts WHERE id=target_id AND (first_vote_ever_at IS NOT NULL OR poll_state='closed')) THEN
 IF TG_OP<>'UPDATE' THEN RAISE EXCEPTION 'Options are frozen' USING ERRCODE='23514';
 ELSIF ROW(NEW.label,NEW.asset_id,NEW.crop_x,NEW.crop_y) IS DISTINCT FROM ROW(OLD.label,OLD.asset_id,OLD.crop_x,OLD.crop_y) THEN RAISE EXCEPTION 'Options are frozen' USING ERRCODE='23514';END IF;END IF;
 IF TG_OP='DELETE' THEN RETURN OLD;END IF;RETURN NEW;END $$;
CREATE TRIGGER protect_frozen_option BEFORE INSERT OR UPDATE OR DELETE ON app_private.post_options FOR EACH ROW EXECUTE FUNCTION app_private.protect_frozen_option();
CREATE FUNCTION app_private.mark_first_ballot() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,app_private AS $$ DECLARE owner_id uuid;BEGIN
 SELECT author_id INTO owner_id FROM app_private.posts WHERE id=NEW.post_id FOR UPDATE;
 IF NEW.validity='valid' AND owner_id=NEW.actor_id THEN RAISE EXCEPTION 'Self vote forbidden' USING ERRCODE='23514';END IF;
 IF NEW.validity='valid' THEN UPDATE app_private.posts SET first_vote_ever_at=COALESCE(first_vote_ever_at,NEW.first_accepted_at) WHERE id=NEW.post_id;END IF;RETURN NEW;END $$;
CREATE TRIGGER mark_first_ballot BEFORE INSERT OR UPDATE ON app_private.ballots FOR EACH ROW EXECUTE FUNCTION app_private.mark_first_ballot();
CREATE TABLE app_private.ballot_notes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),ballot_id uuid NOT NULL UNIQUE REFERENCES app_private.ballots(id) ON DELETE CASCADE,text text NOT NULL CHECK(length(btrim(text))>0 AND octet_length(text)<=16384),moderation text NOT NULL DEFAULT 'checking' CHECK(moderation IN ('checking','visible','held','rejected','deleted')),created_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz);
CREATE TABLE app_private.final_revisions(post_id uuid REFERENCES app_private.posts(id) ON DELETE CASCADE,revision integer CHECK(revision>0),choice text NOT NULL CHECK(choice IN ('A','B','neither')),recorded_at timestamptz NOT NULL DEFAULT now(),poll_snapshot jsonb NOT NULL,reason text NOT NULL DEFAULT '',PRIMARY KEY(post_id,revision));
ALTER TABLE app_private.posts ADD CONSTRAINT posts_final_fk FOREIGN KEY(id,final_revision) REFERENCES app_private.final_revisions(post_id,revision) DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE app_private.reviews(post_id uuid,final_revision integer,score integer NOT NULL CHECK(score BETWEEN 1 AND 10),note text NOT NULL DEFAULT '' CHECK(octet_length(note)<=16384),revision integer NOT NULL DEFAULT 1 CHECK(revision>0),first_reviewed_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(post_id,final_revision),FOREIGN KEY(post_id,final_revision) REFERENCES app_private.final_revisions(post_id,revision) ON DELETE CASCADE);
CREATE TABLE app_private.review_reminders(post_id uuid,final_revision integer,state text NOT NULL DEFAULT 'not_due' CHECK(state IN ('not_due','due','postponed','dismissed','answered')),postponement_count integer NOT NULL DEFAULT 0 CHECK(postponement_count BETWEEN 0 AND 1),first_due_at timestamptz NOT NULL,last_due_at timestamptz,postponed_due_at timestamptz,badge_expires_at timestamptz,revision integer NOT NULL DEFAULT 1,PRIMARY KEY(post_id,final_revision),FOREIGN KEY(post_id,final_revision) REFERENCES app_private.final_revisions(post_id,revision) ON DELETE CASCADE);
CREATE TABLE app_private.outcomes(post_id uuid PRIMARY KEY,final_revision integer NOT NULL,text text NOT NULL DEFAULT '' CHECK(octet_length(text)<=16384),asset_id uuid REFERENCES app_private.assets(id) ON DELETE SET NULL,moderation text NOT NULL DEFAULT 'checking' CHECK(moderation IN ('checking','visible','held','rejected','deleted')),revision integer NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(post_id,final_revision) REFERENCES app_private.final_revisions(post_id,revision) ON DELETE CASCADE);
CREATE TABLE app_private.history_shares(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),post_id uuid NOT NULL UNIQUE REFERENCES app_private.posts(id) ON DELETE CASCADE,audience text NOT NULL DEFAULT 'self' CHECK(audience IN ('self','friends','public')),snapshot jsonb NOT NULL DEFAULT '{}',source_revision integer NOT NULL,final_revision integer NOT NULL,preview_hash text NOT NULL,enabled boolean NOT NULL DEFAULT false,revision integer NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL DEFAULT now(),CHECK(jsonb_typeof(snapshot)='object'),CHECK(NOT(snapshot ?| ARRAY['ballots','responders','votes','voteNotes','inviteToken','authorId'])));
CREATE TABLE app_private.invites(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),post_id uuid NOT NULL REFERENCES app_private.posts(id) ON DELETE CASCADE,token_digest text NOT NULL UNIQUE,policy_revision integer NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),revoked_at timestamptz);
CREATE UNIQUE INDEX one_live_invite ON app_private.invites(post_id) WHERE revoked_at IS NULL;
CREATE TABLE app_private.invite_grants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),invite_id uuid NOT NULL REFERENCES app_private.invites(id) ON DELETE CASCADE,actor_id uuid REFERENCES app_private.actors(id) ON DELETE CASCADE,grant_digest text NOT NULL UNIQUE,policy_revision integer NOT NULL,expires_at timestamptz NOT NULL,revoked_at timestamptz);
CREATE TABLE app_private.guest_claims(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),guest_actor_id uuid NOT NULL REFERENCES app_private.actors(id) ON DELETE CASCADE,post_id uuid NOT NULL REFERENCES app_private.posts(id) ON DELETE CASCADE,nonce_digest text NOT NULL UNIQUE,flow_digest text NOT NULL,expires_at timestamptz NOT NULL,used_at timestamptz,redeemed_by uuid REFERENCES app_private.actors(id) ON DELETE SET NULL);
CREATE TABLE app_private.web_sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),actor_id uuid REFERENCES app_private.actors(id) ON DELETE CASCADE,session_digest text NOT NULL UNIQUE,encrypted_auth_session bytea NOT NULL,expires_at timestamptz NOT NULL,revoked_at timestamptz);
CREATE TABLE app_private.reauth_challenges(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),actor_id uuid NOT NULL REFERENCES app_private.actors(id) ON DELETE CASCADE,initiating_session_digest text NOT NULL,ticket_digest text UNIQUE,created_at timestamptz NOT NULL DEFAULT now(),verified_at timestamptz,expires_at timestamptz NOT NULL,used_at timestamptz);
CREATE TABLE app_private.watches(post_id uuid REFERENCES app_private.posts(id) ON DELETE CASCADE,actor_id uuid REFERENCES app_private.actors(id) ON DELETE CASCADE,push_enabled boolean NOT NULL DEFAULT false,outcome_push_enabled boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(post_id,actor_id));
CREATE TABLE app_private.reposts(post_id uuid REFERENCES app_private.posts(id) ON DELETE CASCADE,actor_id uuid REFERENCES app_private.actors(id) ON DELETE CASCADE,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(post_id,actor_id));
CREATE TABLE app_private.notification_preferences(actor_id uuid PRIMARY KEY REFERENCES app_private.actors(id) ON DELETE CASCADE,friend_posts boolean NOT NULL DEFAULT true,final_updates boolean NOT NULL DEFAULT true,own_actions boolean NOT NULL DEFAULT true,friend_requests boolean NOT NULL DEFAULT true,dna_updates boolean NOT NULL DEFAULT false,private_preview boolean NOT NULL DEFAULT false,quiet_enabled boolean NOT NULL DEFAULT true,quiet_start integer NOT NULL DEFAULT 1380 CHECK(quiet_start BETWEEN 0 AND 1439),quiet_end integer NOT NULL DEFAULT 480 CHECK(quiet_end BETWEEN 0 AND 1439),timezone text NOT NULL DEFAULT 'Asia/Tokyo',revision integer NOT NULL DEFAULT 1);
CREATE TABLE app_private.devices(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),actor_id uuid NOT NULL REFERENCES app_private.actors(id) ON DELETE CASCADE,installation_digest text NOT NULL UNIQUE,encrypted_push_token bytea,platform text NOT NULL CHECK(platform IN ('ios','android')),timezone text NOT NULL,enabled boolean NOT NULL DEFAULT true,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app_private.jobs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),kind text NOT NULL,dedupe_key text NOT NULL UNIQUE,object_id uuid,recipient_id uuid REFERENCES app_private.actors(id) ON DELETE CASCADE,object_version integer,due_at timestamptz NOT NULL,state text NOT NULL DEFAULT 'pending' CHECK(state IN ('pending','leased','done','cancelled','expired','dead')),attempts integer NOT NULL DEFAULT 0 CHECK(attempts>=0),lease_until timestamptz,last_error_code text,payload_ids jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app_private.notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),recipient_id uuid NOT NULL REFERENCES app_private.actors(id) ON DELETE CASCADE,dedupe_key text NOT NULL UNIQUE,kind text NOT NULL,object_id uuid,action_state text NOT NULL DEFAULT 'info' CHECK(action_state IN ('info','required','snoozed','resolved','expired')),read_at timestamptz,snoozed_until timestamptz,provider_ticket text,delivery_state text NOT NULL DEFAULT 'not_sent' CHECK(delivery_state IN ('not_sent','accepted','delivered','failed','unknown')),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app_private.reports(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reporter_id uuid NOT NULL REFERENCES app_private.actors(id) ON DELETE CASCADE,subject_type text NOT NULL CHECK(subject_type IN ('post','note','profile','history')),subject_id uuid NOT NULL,reason_code text NOT NULL,detail text NOT NULL DEFAULT '',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(reporter_id,subject_type,subject_id));
CREATE TABLE app_private.moderation_cases(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),subject_type text NOT NULL,subject_id uuid NOT NULL,subject_version integer NOT NULL,state text NOT NULL CHECK(state IN ('checking','held','allowed','rejected','appealed','closed')),risk text NOT NULL DEFAULT 'unknown' CHECK(risk IN ('unknown','low','medium','high')),reason_codes jsonb NOT NULL DEFAULT '[]',model_version text,assigned_to uuid REFERENCES app_private.actors(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app_private.moderation_actions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),case_id uuid NOT NULL REFERENCES app_private.moderation_cases(id) ON DELETE CASCADE,staff_actor_id uuid REFERENCES app_private.actors(id) ON DELETE SET NULL,action text NOT NULL,reason text NOT NULL,subject_version integer NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app_private.appeals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),case_id uuid NOT NULL REFERENCES app_private.moderation_cases(id) ON DELETE CASCADE,actor_id uuid NOT NULL REFERENCES app_private.actors(id) ON DELETE CASCADE,detail text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(case_id,actor_id));
CREATE TABLE app_private.staff_members(actor_id uuid PRIMARY KEY REFERENCES app_private.actors(id) ON DELETE CASCADE,role text NOT NULL CHECK(role IN ('moderator','admin')),enabled boolean NOT NULL DEFAULT true);
CREATE TABLE app_private.idempotency_keys(principal_digest text,operation text,key uuid,payload_hash text NOT NULL,response_status integer,safe_response jsonb,encrypted_secret_response bytea,expires_at timestamptz NOT NULL,PRIMARY KEY(principal_digest,operation,key));
CREATE TABLE app_private.rate_windows(scope_digest text,kind text,window_start timestamptz,count integer NOT NULL DEFAULT 0 CHECK(count>=0),PRIMARY KEY(scope_digest,kind,window_start));
CREATE TABLE app_private.dna_snapshots(actor_id uuid PRIMARY KEY REFERENCES app_private.actors(id) ON DELETE CASCADE,algorithm_version text NOT NULL,state text NOT NULL CHECK(state IN ('collecting','starting','trend','insufficient','ready')),type_name text CHECK(type_name IN ('一番星','舵取り','目利き','勝負師','策士','切り札','道しるべ','開拓者')),review_count integer NOT NULL CHECK(review_count>=0),observed_metrics jsonb NOT NULL DEFAULT '{}',input_version integer NOT NULL,displayed_review_ids jsonb NOT NULL DEFAULT '[]',displayed_at timestamptz,CHECK(state<>'ready' OR (review_count>=10 AND type_name IS NOT NULL)));
CREATE TABLE app_private.analytics_events(id uuid PRIMARY KEY,event_name text NOT NULL,analysis_actor_digest text,actor_kind text NOT NULL CHECK(actor_kind IN ('account','guest','reader')),post_id uuid REFERENCES app_private.posts(id) ON DELETE SET NULL,safe_dimensions jsonb NOT NULL DEFAULT '{}',schema_version integer NOT NULL DEFAULT 1,occurred_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app_private.feature_flags(name text PRIMARY KEY CHECK(name IN ('public_guest_pilot','public_repost','decision_watch','public_follow_emphasis','opinion_poll','question_remix','history_search')),enabled boolean NOT NULL DEFAULT false,updated_at timestamptz NOT NULL DEFAULT now());
INSERT INTO app_private.feature_flags(name) VALUES('public_guest_pilot'),('public_repost'),('decision_watch'),('public_follow_emphasis'),('opinion_poll'),('question_remix'),('history_search');
CREATE TABLE app_private.deletion_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),actor_id uuid REFERENCES app_private.actors(id) ON DELETE SET NULL,subject_type text NOT NULL CHECK(subject_type IN ('post','account')),subject_id uuid NOT NULL,state text NOT NULL DEFAULT 'pending' CHECK(state IN ('pending','running','done','failed')),requested_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,last_error_code text);
CREATE INDEX posts_open_due ON app_private.posts(ends_at,id) WHERE poll_state='open' AND publication<>'deleted';
CREATE INDEX posts_author_time ON app_private.posts(author_id,created_at DESC,id);
CREATE INDEX posts_public_time ON app_private.posts(published_at DESC,id) WHERE audience='public' AND publication='visible';
CREATE INDEX audience_by_actor ON app_private.audience_members(actor_id,post_id);
CREATE INDEX ballots_count ON app_private.ballots(post_id,choice) WHERE validity='valid';
CREATE INDEX ballots_actor ON app_private.ballots(actor_id,first_accepted_at DESC);
CREATE INDEX anonymous_recent ON app_private.anonymous_usage(author_id,created_at);
CREATE INDEX jobs_due ON app_private.jobs(due_at,id) WHERE state='pending';
CREATE INDEX jobs_lease ON app_private.jobs(lease_until) WHERE state='leased';
CREATE INDEX notifications_recipient ON app_private.notifications(recipient_id,created_at DESC,id);
CREATE INDEX moderation_queue ON app_private.moderation_cases(state,created_at);
CREATE INDEX reports_subject ON app_private.reports(subject_type,subject_id,created_at);
DO $$ DECLARE entry record; BEGIN FOR entry IN SELECT tablename FROM pg_tables WHERE schemaname='app_private' LOOP EXECUTE format('ALTER TABLE app_private.%I ENABLE ROW LEVEL SECURITY',entry.tablename);EXECUTE format('ALTER TABLE app_private.%I FORCE ROW LEVEL SECURITY',entry.tablename);END LOOP;END $$;
REVOKE ALL ON ALL TABLES IN SCHEMA app_private FROM PUBLIC,anon,authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA app_private FROM PUBLIC,anon,authenticated;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA app_private FROM PUBLIC,anon,authenticated;
GRANT USAGE ON SCHEMA app_private TO service_role;
GRANT ALL ON ALL TABLES IN SCHEMA app_private TO service_role;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA app_private TO service_role;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA app_private TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA app_private REVOKE ALL ON TABLES FROM PUBLIC,anon,authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA app_private REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC,anon,authenticated;
COMMIT;
