import test from 'node:test';import assert from 'node:assert/strict';import * as d from '../reference/domain.ts';
const post=(x={})=>({id:'p',authorId:'owner',audience:'friends_link',anonymous:false,voteMode:'named',publication:'visible',state:'open',duration:'3h',endsAt:3*d.HOUR,closedAt:null,extensionUsed:false,firstVoteEverAt:null,fixedFinalDueAt:null,revision:1,...x});
const viewer=(x={})=>({actorId:'v',friendAtPublish:true,friendNow:true,blocked:false,validGrant:false,registered:true,publicGuestAllowed:false,...x});
const ballot=(x={})=>({postId:'p',actorId:'v',choice:'A',origin:'account',firstAt:0,lockedAt:null,changes:0,validity:'valid',revision:1,...x});
test('NFC and multiline normalization',()=>{assert.equal(d.normalizeText(' e\u0301\nA '),'é A');assert.equal(d.normalizeText('a\r\nb',true),'a\nb')});
test('graphemes count emoji families as one',()=>assert.equal(d.graphemeCount('👨‍👩‍👧‍👦が'),2));
test('exact limits accepted',()=>assert.equal(d.validatePostText('あ'.repeat(80),'A'.repeat(30),'B'.repeat(30),'補'.repeat(300)).question.length,80));
test('overflow and blank rejected',()=>{assert.throws(()=>d.validatePostText('あ'.repeat(81),'a','b'));assert.throws(()=>d.validatePostText(' ','a','b'))});
test('duplicate options after normalization rejected',()=>assert.throws(()=>d.validatePostText('q','a ','a')));
test('friend must belong to snapshot and current relation',()=>{assert.equal(d.canView(post({audience:'friends'}),viewer({friendAtPublish:false})),false);assert.equal(d.canView(post({audience:'friends'}),viewer({friendNow:false})),false)});
test('invite grants access without friendship',()=>assert.equal(d.canView(post(),viewer({friendNow:false,friendAtPublish:false,validGrant:true})),true));
test('revoked invite loses access even with past vote',()=>assert.equal(d.canView(post(),viewer({friendNow:false,validGrant:false})),false));
test('block wins over invite grant',()=>assert.equal(d.canView(post(),viewer({blocked:true,validGrant:true})),false));
test('held only visible to owner; deleted not to owner',()=>{assert.equal(d.canView(post({publication:'held'}),viewer()),false);assert.equal(d.canView(post({publication:'held'}),viewer({actorId:'owner'})),true);assert.equal(d.canView(post({publication:'deleted'}),viewer({actorId:'owner'})),false)});
test('0 votes extend exactly once from original deadline',()=>{const p=d.settle(post(),[],3*d.HOUR);assert.equal(p.endsAt,6*d.HOUR);assert.equal(p.extensionUsed,true);assert.equal(d.settle(p,[],6*d.HOUR).state,'closed')});
for(const [preset,delta] of [['1h',d.HOUR],['3h',3*d.HOUR],['1d',d.DAY],['1w',d.DAY]])test('extension '+preset,()=>assert.equal(d.settle(post({duration:preset}),[],3*d.HOUR).endsAt,3*d.HOUR+delta));
test('15m and custom never extend',()=>{for(const duration of ['15m','custom'])assert.equal(d.settle(post({duration}),[],3*d.HOUR).state,'closed')});
test('late Cron closes even after extension',()=>{const p=d.settle(post(),[],10*d.HOUR);assert.equal(p.state,'closed');assert.equal(p.closedAt,6*d.HOUR)});
test('fixed final deadline caps extension',()=>assert.equal(d.settle(post({fixedFinalDueAt:4*d.HOUR}),[],3*d.HOUR).state,'closed'));
test('one mutable accepted ballot prevents 0-vote extension',()=>assert.equal(d.settle(post(),[ballot()],3*d.HOUR).state,'closed'));
test('manual close never extends',()=>assert.equal(d.manualClose(post(),d.HOUR).extensionUsed,false));
test('self vote forbidden',()=>assert.throws(()=>d.cast(post(),viewer({actorId:'owner'}),[],'A',1),/SELF_VOTE/));
test('R1 public guest disabled',()=>assert.throws(()=>d.cast(post({audience:'public'}),viewer({registered:false}),[],'A',1),/ACTION_FORBIDDEN/));
test('link guest accepted without forced registration',()=>assert.equal(d.cast(post(),viewer({registered:false,validGrant:true}),[],'A',1).ballot.origin,'guest'));
test('cast freezes source without bumping post revision for every vote',()=>{const r=d.cast(post(),viewer(),[],'A',1);assert.equal(r.post.firstVoteEverAt,1);assert.equal(r.post.revision,1);assert.equal(d.canEditSource(r.post),false)});
test('first vote marker stays frozen when all ballots invalid',()=>assert.equal(d.canEditSource(post({firstVoteEverAt:0})),false));
test('closed zero-vote source cannot be repurposed',()=>assert.equal(d.canEditSource(post({state:'closed',firstVoteEverAt:null})),false));
test('duplicate vote rejected',()=>assert.throws(()=>d.cast(post(),viewer(),[ballot()],'B',1),/ALREADY_VOTED/));
test('299999ms mutable; 300000ms locked',()=>{assert.equal(d.ballotState(post(),ballot(),299999),'mutable');assert.equal(d.ballotState(post(),ballot(),300000),'locked')});
test('same choice no-op; one change locks',()=>{assert.equal(d.change(post(),ballot(),'A',1).changes,0);const b=d.change(post(),ballot(),'B',1);assert.equal(b.changes,1);assert.throws(()=>d.change(post(),b,'A',2),/BALLOT_LOCKED/)});
test('instant lock reveals result only to non-author',()=>{const b=d.lock(post(),ballot(),10);assert.equal(d.resultProjection(post(),viewer(),[b],11).kind,'available');assert.equal(d.resultProjection(post(),viewer({actorId:'owner'}),[b],11).kind,'hidden')});
test('unvoted and mutable never receive counts',()=>{assert.deepEqual(d.resultProjection(post(),viewer(),[],1),{kind:'hidden'});assert.deepEqual(d.resultProjection(post(),viewer(),[ballot()],1),{kind:'hidden'})});
test('zero/tie/rounding display',()=>{assert.equal(d.percentages(0,0),null);assert.equal(d.percentages(1,1).label,'同数');assert.equal(d.percentages(1,2).a+d.percentages(1,2).b,100)});
test('anonymous author projection excludes id',()=>{const p=d.authorProjection(post({anonymous:true}),'v');assert.equal('id' in p,false);assert.equal(p.label,'匿名の友達')});
test('public participants hidden from owner',()=>assert.deepEqual(d.participantProjection(post({voteMode:'participation_hidden'}),viewer({actorId:'owner'}),[ballot()]),[]));
test('named identities only reveal choice after close',()=>{assert.equal('choice' in d.participantProjection(post(),viewer({actorId:'owner'}),[ballot()])[0],false);assert.equal(d.participantProjection(post({state:'closed'}),viewer(),[ballot()])[0].choice,'A')});
test('guest-origin identity never listed after registration',()=>assert.deepEqual(d.participantProjection(post({state:'closed'}),viewer(),[ballot({origin:'guest'})]),[]));
test('merge keeps existing account ballot and count',()=>{const r=d.mergeGuest(post(),ballot({origin:'guest'}),ballot({actorId:'account',choice:'B'}),'account');assert.equal(r.account.choice,'B');assert.equal(r.guest.validity,'merged')});
test('merge preserves old timestamp and locked anonymous origin',()=>{const r=d.mergeGuest(post(),ballot({origin:'guest',firstAt:20,changes:1,lockedAt:30}),null,'account');assert.equal(r.account.firstAt,20);assert.equal(r.account.lockedAt,30);assert.equal(r.account.origin,'guest')});
test('merge to owner invalidates self-vote',()=>assert.equal(d.mergeGuest(post(),ballot(),null,'owner').guest.validity,'invalid'));
test('history whitelist excludes respondents and ballots',()=>{const r=d.historyProjection({anonymous:false,question:'q',A:'a',B:'b',final:'A',votes:[1],responders:['v'],score:8},{score:true,note:false});assert.equal('votes' in r,false);assert.equal('responders' in r,false);assert.equal(r.score,8)});
test('anonymous history cannot be shared',()=>assert.throws(()=>d.historyProjection({anonymous:true,question:'q',A:'a',B:'b',final:'A'},{score:false,note:false})));
test('next day deadline is local calendar end',()=>assert.equal(new Date(d.finalDue(Date.parse('2026-09-10T15:30:00Z'),'next_day','Asia/Tokyo')).toISOString(),'2026-09-12T14:59:59.000Z'));
test('DST calendar end calculation',()=>assert.equal(new Date(d.finalDue(Date.parse('2026-03-07T18:00:00Z'),'next_day','America/New_York')).toISOString(),'2026-03-09T03:59:59.000Z'));
test('review two reminders, answer/dismiss cancel, postpone replaces',()=>{assert.deepEqual(d.reviewSchedule(0),[3*d.DAY,6*d.DAY]);assert.deepEqual(d.reviewSchedule(0,{answered:true}),[]);assert.deepEqual(d.reviewSchedule(0,{dismissed:true}),[]);assert.deepEqual(d.reviewSchedule(0,{postponedAt:10}),[10])});
test('postponement from action once, future and 180d bounds',()=>{assert.equal(d.postpone(d.DAY,0),8*d.DAY);assert.throws(()=>d.postpone(0,1));assert.throws(()=>d.postpone(0,0,181*d.DAY));assert.throws(()=>d.postpone(0,0,0))});
test('quiet hours local wrap around, end exclusive',()=>{assert.equal(d.quietTime(Date.parse('2026-09-10T14:00:00Z'),'Asia/Tokyo'),true);assert.equal(d.quietTime(Date.parse('2026-09-10T23:00:00Z'),'Asia/Tokyo'),false)});
const entries=(n,x={})=>Array.from({length:n},(_,i)=>({postId:String(i),intent:'decision',current:true,deleted:false,final:'A',closedAt:0,finalAt:d.HOUR,reviewedAt:i,score:8,a:1,b:3,...x}));
test('DNA staged unlock',()=>{assert.equal(d.dna(entries(2)).state,'collecting');assert.equal(d.dna(entries(4)).state,'starting');assert.equal(d.dna(entries(9)).state,'trend');assert.equal(d.dna(entries(10)).type,'一番星')});
test('DNA cannot infer majority from 0 votes/neither',()=>assert.equal(d.dna(entries(10,{final:'neither',a:0,b:0})).state,'insufficient'));
test('DNA excludes Poll/deleted/old versions and duplicates',()=>{assert.equal(d.dna(entries(10,{intent:'poll'})).count,0);assert.equal(d.dna([...entries(10),...entries(10)]).count,10);assert.equal(d.dna(entries(10,{current:false})).count,0)});
test('DNA all eight mappings',()=>{const names=['道しるべ','目利き','切り札','舵取り','開拓者','策士','勝負師','一番星'];for(let key=0;key<8;key++){const data=entries(10,{a:key&4?1:3,b:key&4?3:1,finalAt:key&2?d.HOUR:8*d.HOUR});if(!(key&1))data.forEach((e,i)=>e.score=i%2?10:1);assert.equal(d.dna(data).type,names[key])}});
test('DNA waits for new count AND time, immediately retracts insufficient',()=>{assert.equal(d.mayUpdateDna(4,0,20*d.DAY),false);assert.equal(d.mayUpdateDna(5,0,13*d.DAY),false);assert.equal(d.mayUpdateDna(5,0,14*d.DAY),true);assert.equal(d.mayUpdateDna(0,0,1,false),true)});
