/* Local design reference. No authentication, network calls or server mutations. */
const $=s=>document.querySelector(s),screens=window.DECIDE_SCREENS;
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let current='S03',state='default',selected=null,locked=false,score=null,finalChoice=null,recordedFinal='A',advanced=false,audience='friends_link',notify='actions',lastFocus=null;
const draft={question:'次の連休、ひとり旅するなら？',A:'韓国',B:'台湾',context:'3泊4日。おいしいものを食べながら、街を歩きたい。'};
const shape={back:'m15 18-6-6 6-6',next:'m9 6 6 6-6 6',plus:'M12 5v14M5 12h14',home:'m3 10 9-7 9 7v10H3zM9 20v-7h6v7',bell:'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4',people:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M20 8v6M17 11h6',more:'M5 12h.01M12 12h.01M19 12h.01',expand:'M9 3H3v6M15 3h6v6M3 15v6h6M21 15v6h-6M3 3l6 6M21 3l-6 6M3 21l6-6M21 21l-6-6',edit:'m16 3 5 5-13 13H3v-5zM13 6l5 5',clock:'M12 8v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',lock:'M6 11h12v10H6zM8 11V7a4 4 0 0 1 8 0v4',camera:'M3 7h4l2-3h6l2 3h4v14H3zM16 14a4 4 0 1 1-8 0 4 4 0 0 1 8 0',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2',qr:'M3 3h6v6H3zM15 3h6v6h-6zM3 15h6v6H3zM15 15h3v3h3v3h-6z',close:'m6 6 12 12M18 6 6 18'};
function icon(n,size=24){return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${shape[n]||shape.next}"/></svg>`}
function ib(n,label,a){return `<button class="icon" aria-label="${label}" data-a="${a}">${icon(n)}</button>`}
function button(label,a='demo',kind='primary',disabled=false){return `<button class="${kind}" data-a="${a}" ${disabled?'disabled':''}>${label}</button>`}
function row(label,detail='',a='demo'){return `<button class="row" data-a="${a}"><span class="grow">${label}${detail?`<small>${detail}</small>`:''}</span>${icon('next',20)}</button>`}
function toggle(label,detail='',checked=false){return `<label class="row"><span class="grow">${label}${detail?`<small>${detail}</small>`:''}</span><input type="checkbox" aria-label="${label}" ${checked?'checked':''}></label>`}
function field(label,value='',key='',multi=false,hint=''){const attrs=key?`data-draft="${key}"`:'';return `<label class="field">${label}${multi?`<textarea ${attrs} rows="3">${esc(value)}</textarea>`:`<input ${attrs} value="${esc(value)}">`}${hint?`<small>${hint}</small>`:''}</label>`}
function brand(){return '<div class="brand"><span class="mark" aria-hidden="true"><i></i><i></i></span>DECIDE</div>'}
function head(title=null,back='S03'){return `<div class="top">${title?ib('back','戻る','go:'+back)+`<h2>${title}</h2>`:brand()}${ib(title?'more':'people',title?'メニュー':'友達を追加',title?'sheet:O05':'go:S20')}</div>`}
function nav(){return `<nav class="bottom" aria-label="主要ナビ">${button(icon('home')+'<span>ホーム</span>','go:S03','nav-item')}${button(icon('plus'),'go:S05','create')}${button(icon('bell')+'<span>通知<span class="badge">3</span></span>','go:S13','nav-item')}${button('<img src="assets/me.jpg" alt=""><span>プロフィール</span>','go:S14','nav-item')}</nav>`}
function author(owner=false,pub=false,anon=false){return `<div class="author">${anon?`<span class="avatar icon" aria-hidden="true">${icon('people')}</span>`:`<img class="avatar" src="assets/${owner?'me':'friend'}.jpg" alt="">`}<div class="author-info"><strong>${anon?'匿名の友達':owner?'あなた':'ゆい'}</strong><p class="subtle">${anon?'友達のみ':pub?'公開':'友達＋リンク'} · 12分前</p></div><span class="pill">あと2時間</span></div>`}
function q(){return state==='long'?'夏休みに友達と行く旅行先をまだ決められずにいます。街歩きもおいしい食事も楽しみたいのですが、初めての海外旅行ならどちらの行き先がおすすめですか？':draft.question}
function pair(vote=true,photos=true){return `<div class="pair ${photos?'':'text-only'}">${['A','B'].map((c,i)=>`<div class="option ${i?'b':''} ${selected===c?'selected':''}">${photos?`<div class="photo"><img src="assets/${i?'taipei':'seoul'}.jpg" alt="${i?'台湾':'韓国'}の街並み">${ib('expand',c+'の写真を拡大','image:'+c)}</div>`:''}<button class="option-button" data-a="${vote?'vote:'+c:'demo'}" aria-label="${c} ${esc(draft[c])}" aria-pressed="${selected===c}"><b>${c}</b><span>${esc(state==='long'?(i?'台湾で夜市の食べ歩きと街歩きをのんびり楽しむ旅':'韓国でカフェ巡りと買い物を心ゆくまで楽しむ旅'):draft[c])}${selected===c?' ✓':''}</span></button></div>`).join('')}</div>`}
function summary(){return `<div class="summary"><p class="question">${esc(draft.question)}</p><div class="mini-pair"><span>A｜${esc(draft.A)}</span><span>B｜${esc(draft.B)}</span></div></div>`}
function result(kind='current'){if(kind==='zero')return '<div class="results"><strong>回答なし</strong><p class="subtle">投票は終了しました。回答がなくても決断を残せます。</p></div>';const tie=kind==='tie';return `<div class="results"><span class="subtle">${tie?'最終結果 · 同数':'現在の結果 · 受付中'}</span><div class="result-labels"><span>A ${tie?'50':'63'}%</span><span>B ${tie?'50':'37'}%</span></div><div class="track"><span ${tie?'style="width:50%"':''}></span><span></span></div><p class="subtle">${tie?'4票ずつ':'韓国 5票 / 台湾 3票'} · 8人<br>投票時：登録票6 / ゲスト票2</p></div>`}
function finalBlock(){const t=recordedFinal==='neither'?'どちらも選びませんでした。':esc(draft[recordedFinal])+'に決めました。';return `<div class="final"><span class="stamp">DECIDED ✓</span><h2>${t}</h2><p class="subtle">あなたの決断 · 9月10日 18:12</p></div>`}
function dnaCard(){return `<div class="dna"><span class="subtle">DECISION DNA</span><h3>少しずつ、見えてきた。</h3><p class="copy">振り返り 6 / 10件</p><div class="progress"><span></span></div>${button('現在の傾向を見る →','go:S19','text-button')}</div>`}
function historyItem(title=draft.question,choice='韓国',s='8 / 10'){return `<div class="history"><p class="subtle">9月10日 · 旅行・おでかけ</p><h3>${esc(title)}</h3><div class="metadata"><span>${choice}に決断</span><strong>${s}</strong></div>${button('記録を見る →','go:S17','text-button')}</div>`}
function feed(pub=false){return head()+`<div class="page"><div class="tabs">${button('友達','go:S03',pub?'':'active')}${button('発見','go:S04',pub?'active':'')}</div>${pub?'<div class="chips"><button class="selected" data-a="demo">おすすめ</button><button data-a="demo">旅行・おでかけ</button></div>':`<button class="notice" data-a="go:S12">${icon('edit')}<span>3日前の決断、どうだった？</span>${icon('next',18)}</button>`}${author(false,pub)}<h2 class="question">${esc(q())}</h2>${pair()}<div class="metadata"><span class="subtle">8人が回答 · ${pub?'参加者非表示':'記名'}</span>${button(pub?'詳細を見る':'リンクを共有',pub?'go:S08':'go:S07','text-button')}</div><div class="update"><img class="avatar" src="assets/friend.jpg" alt=""><div class="grow"><p class="subtle">参加した相談、その後</p><strong>ゆいは、韓国にしました。</strong></div><span class="stamp">DECIDED ✓</span></div></div>`+nav()}
function detail(guest=false){const owner=state==='owner',closed=['closed','zero'].includes(state);return head(guest?'相談が届いています':'相談')+`<div class="page">${author(owner,false,state==='anonymous')}<h2 class="question">${esc(q())}</h2>${pair(!owner&&!closed,state!=='long')}<p class="copy">${esc(draft.context)}</p><div class="metadata"><span class="subtle">${state==='zero'?'0':'8'}人が回答 · 記名</span><span class="subtle">${closed?'受付終了':'あと2時間'}</span></div>${owner?`<div class="notice">${icon('lock')}<span>結果は投票終了後に見られます</span></div>${button('今決める','sheet:O08')}`:closed?result(state==='zero'?'zero':'tie'):locked?result():selected?`<div class="notice"><span>${selected}に投票しました。変更は残り1回です。</span></div>${button('この投票で確定して結果を見る','lock')}${button('選択を1回だけ変更','sheet:O07','secondary')}`:'<p class="subtle">AかBをタップして投票。選ばずに戻っても大丈夫。</p>'}${selected?row('ひとことを添える','任意・80文字・投票終了後に表示','sheet:O04'):''}${guest&&locked?button('本人の決断も知りたい','go:W02'):''}${guest?'<p class="subtle" style="margin-top:18px">登録せずに投票できます。ゲスト票は匿名です。</p>':''}</div>`}
function profile(other=false){return head(other?'プロフィール':'マイページ')+`<div class="page"><div class="cover"></div><img class="profile-photo" src="assets/${other?'friend':'me'}.jpg" alt="プロフィール写真"><h2 class="profile-name">${other?'ゆい':'れん'}</h2><p class="subtle">@${other?'yui':'ren'}</p><p class="copy">旅とコーヒー。ときどき、みんなに聞いてみる。</p>${other?button('友達申請する','demo')+button('フォローする','demo','text-button'):button('プロフィールを編集','go:S22','secondary')}<div class="stats"><div><strong>${other?'4':'12'}</strong><span>${other?'共有された決断':'Decision'}</span></div><div><strong>${other?'8.0':'8.2'}</strong><span>平均満足度</span></div><div><strong>旅行</strong><span>よく相談する</span></div></div>${other?'':dnaCard()}${row(other?'共有された記録':'意思決定の履歴','選んだこと。その後のこと。',other?'go:S17':'go:S16')}${other?'':row('設定','','go:S23')}</div>`+(other?'':nav())}
function feedback(){if(state==='loading')return head('読み込み中')+'<div class="page" aria-busy="true"><div class="skeleton"></div><div class="skeleton large"></div><div class="skeleton"></div></div>';const empty=state==='empty';return head(screens.find(s=>s.id===current).name)+`<div class="page"><div class="empty"><div class="orb">${icon(empty?'plus':'clock',36)}</div><h2>${empty?'まだ、相談がありません':'接続できませんでした'}</h2><p class="subtle">${empty?'小さな迷いから、友達に聞いてみよう。':'入力内容は残っています。接続を確認して、もう一度お試しください。'}</p>${button(empty?'相談を書く':'もう一度試す',empty?'go:S05':'retry')}</div></div>`}
function screenContent(){if(['loading','empty','error'].includes(state))return feedback();switch(current){
case'S01':return head()+`<div class="page welcome"><p class="subtle">ひとりで迷うを、みんなで選ぶに。</p><h2>聞いてみよう。<br>決めるのは、<br>あなた。</h2><div class="mini-pair"><span>A｜こっち？</span><span>B｜それとも？</span></div><p class="copy">友達に聞いて、選んで、振り返る。<br>あなたの決断が、あなたの記録になる。</p>${button('Appleで続ける','go:S02')}${button('Googleで続ける','go:S02','secondary')}${button('公開されている相談を見る','go:S04','text-button')}</div>`;
case'S02':return head('はじめまして','S01')+`<div class="page"><h2 class="question">どう呼ばれたい？</h2>${field('表示名','れん')}${field('@ID','ren','','','英小文字・数字・_、3〜20文字')}${toggle('18歳以上です','初期ベータの参加条件')}${toggle('利用規約・プライバシーポリシーに同意')}${button('DECIDEをはじめる','go:S03')}<p class="subtle">設計見本のためアカウントは作成されません。</p></div>`;
case'S03':return feed();case'S04':return feed(true);
case'S05':return head('相談を書く')+`<div class="page"><p class="subtle">1 / 2 · まずは、二択だけ。</p>${field('何に迷ってる？',draft.question,'question',true,'最大80文字')}<div class="option-field">${field('A',draft.A,'A',false,'最大30文字')}${button('写真を追加','sheet:O01','text-button')}</div><div class="option-field b">${field('B',draft.B,'B',false,'最大30文字')}${button('写真を追加','sheet:O01','text-button')}</div>${field('補足（任意）',draft.context,'context',true,'最大300文字・URL可')}<p class="subtle" id="input-error" role="alert"></p>${button('次へ','next-compose')}</div>`;
case'S06':return head('この内容で相談する','S05')+`<div class="page"><p class="subtle">2 / 2 · 設定はこのままでも大丈夫。</p>${summary()}${row(audience==='public'?'公開':audience==='friends'?'友達のみ':'友達＋招待リンク',audience==='public'?'参加者は表示されません':'相談ごとに範囲を選べます','settings')}${row('投票は3時間','9月10日 18:00まで','sheet:O02')}${row('決める目安は翌日','9月11日 23:59まで','sheet:O02')}${row('投票方法：'+(audience==='public'?'参加者非表示':'記名'),audience==='public'?'公開では固定です':'終了後に選択別アイコンを表示','settings')}${advanced?`<div class="summary"><h3>公開範囲</h3><div class="chips">${[['friends','友達のみ'],['friends_link','友達＋リンク'],['public','公開']].map(([v,t])=>button(t,'audience:'+v,audience===v?'selected':'')).join('')}</div>${audience==='friends'?row('相談する友達','全員 / 選んだ友達','sheet:O03')+toggle('匿名で相談','友達全員のみ・利用条件あり'):''}</div>`:''}${button('相談する','go:S07')}<p class="subtle" style="margin-top:14px">投稿内容は公開前に確認されます。</p></div>`;
case'S07':return head('相談を受け付けました')+`<div class="page">${summary()}<div class="notice">${icon('clock')}<span>内容を確認しています</span></div><p class="copy">公開されたら、友達にリンクを送れます。投票時間は公開時から数えます。</p>${button('リンクを共有','demo','primary',true)}${button('ホームへ','go:S03','secondary')}</div>`;
case'S08':return detail();case'S09':if(!selected)selected='A';return detail();
case'S10':return head('あなたは、どうする？','S08')+`<div class="page"><p class="subtle">投票は終了しました</p><h2 class="question">${esc(draft.question)}</h2>${result('tie')}<div class="chips">${[['A','A｜韓国'],['B','B｜台湾'],['neither','どちらも選ばなかった']].map(([v,t])=>button(t,'final:'+v,finalChoice===v?'selected':'')).join('')}</div>${button('この決断を記録する','save-final','primary',!finalChoice)}${button('まだ決めていない','defer','text-button')}<p class="subtle">多数決に従わなくても大丈夫。選ぶのはあなたです。</p></div>`;
case'S11':return head('その後、どうなった？','S17')+`<div class="page">${finalBlock()}${field('ひとこと（任意）','','',true,'最大80文字')}${button('写真を1枚添える','sheet:O01','secondary')}${button('その後を保存','demo')}</div>`;
case'S12':return head('振り返る','S13')+`<div class="page"><p class="subtle">韓国を選んでから3日</p><h2 class="question">この決断、どれくらい満足してる？</h2><div class="scores">${Array.from({length:10},(_,i)=>`<button class="score ${score===i+1?'selected':''}" data-a="score:${i+1}" aria-label="満足度 ${i+1}" aria-pressed="${score===i+1}">${i+1}</button>`).join('')}</div><div class="scale-labels subtle"><span>1 · まったく<br>満足していない</span><span>10 · とても<br>満足している</span></div>${field('ひとこと残す（任意）','','',true,'最大300文字')}<p class="subtle">自分だけに保存。共有はあとから選べます。</p>${button('振り返りを保存','save-review','primary',score===null)}${button('まだ結果が分からない','sheet:O10','text-button')}${button('今回は振り返らない','dismiss','text-button')}</div>`;
case'S13':return head('通知')+`<div class="page"><div class="tabs">${button('対応が必要 3','notify:actions',notify==='actions'?'active':'')}${button('お知らせ','notify:info',notify==='info'?'active':'')}</div>${notify==='actions'?row('あなたの決断を残そう','投票が終了しました','go:S10')+row('韓国の旅、どうだった？','振り返りの時間です','go:S12')+row('ゆいから友達申請','承認すると、お互いに相談できます','go:S20'):row('ゆいが、韓国に決めました','参加した相談・2時間前','go:S17')+row('相談に3人が回答','結果は投票終了後に確認できます','go:S08')}</div>`+nav();
case'S14':return profile();case'S15':return profile(true);
case'S16':return head('意思決定の履歴','S14')+`<div class="page"><div class="tabs">${button('完了','demo','active')}${button('進行中','go:S08','')}</div><div class="chips">${button('すべて','demo','selected')}${button('旅行','demo','')}${button('買い物','demo','')}</div><h2 class="question">2026年9月</h2>${historyItem()}${historyItem('週末、新しい靴を買うなら？','白いスニーカー','未回答')}</div>`;
case'S17':return head('決断の記録','S16')+`<div class="page"><p class="subtle">9月10日・自分だけ</p><h2 class="question">${esc(draft.question)}</h2>${finalBlock()}<h3>振り返り</h3><p class="copy"><strong>${score??8} / 10</strong> の満足度</p><p class="copy">カフェと街歩き、どちらも楽しめた。ひとり旅にしてよかった。</p><p class="subtle">9月13日記録・最新版の決断への評価</p>${row('相談と投票結果を見る','元の公開範囲が適用されます','go:S08')}${row('その後を残す','写真は1枚まで','go:S11')}${button('この記録の公開範囲','go:S18','secondary')}</div>`;
case'S18':return head('記録を共有する','S17')+`<div class="page"><h2 class="question">見せたいことだけ。</h2><p class="copy">あなたの決断の記録を共有します。友達の票や回答者、ひとことは含まれません。</p>${toggle('その後を含める')}${toggle('満足度を含める','8 / 10')}${toggle('振り返りのメモを含める')}<div class="chips">${button('自分だけ','demo','selected')}${button('友達','demo','')}${button('公開','demo','')}</div>${summary()}<p class="subtle">共有対象：質問・A/B・あなたの最終決断。元の相談の公開範囲は変わりません。</p>${button('この内容を確認する','demo')}</div>`;
case'S19':return head('Decision DNA','S14')+`<div class="page">${dnaCard()}<h2 class="question">最近の記録から</h2>${row('よく相談したのは旅行','6件のうち3件')}${row('平均満足度は8.2','未回答を0点として数えません')}<p class="copy">10件以上と必要な比較データが集まったら、8タイプのいずれかを表示します。</p><p class="subtle">人格や能力の診断ではありません。データが足りない場合は、件数を満たしても分析中になります。</p>${button('履歴を見てみる','go:S16','secondary')}</div>`;
case'S20':return head('友達')+`<div class="page">${field('名前・@IDで探す')}<div class="tabs">${button('友達','demo','active')}${button('申請 1','demo','')}</div><div class="author"><img class="avatar" src="assets/friend.jpg" alt=""><div class="author-info"><strong>ゆい</strong><p class="subtle">@yui · 友達申請が届いています</p></div></div>${button('友達申請を承認','demo')}${button('今は承認しない','demo','text-button')}${row('QRでつながる','読み取ってから申請します','go:S21')}${row('プロフィールを見る','','go:S15')}</div>`;
case'S21':return head('QRでつながる','S20')+`<div class="page"><h2 class="question">会ったら、その場で。</h2><div class="qr">${icon('qr',80)}<span class="subtle">QR配置見本・読み取り不可</span></div><p class="copy" style="text-align:center">れん · @ren</p><p class="subtle">QRを読み取ると、友達申請の画面が開きます。</p>${button('QRを読み取る','demo','secondary')}</div>`;
case'S22':return head('プロフィール編集','S14')+`<div class="page">${field('表示名','れん')}${field('@ID','ren','','','3〜20文字・変更は30日に1回')}${field('自己紹介','旅とコーヒー。ときどき、みんなに聞いてみる。','',true,'最大80文字')}${field('16タイプ（任意）')}<p class="subtle">自己申告の16タイプはDecision DNAとは別です。</p><div class="chips">${button('ライラック','demo','selected')}${button('ライム','demo','')}${button('ニュートラル','demo','')}</div>${button('保存する','demo')}</div>`;
case'S23':return head('設定','S14')+`<div class="page">${row('プロフィール','','go:S22')}${row('通知','','go:S24')}${row('プロフィールの公開項目','','go:S25')}${row('ブロックしたアカウント','','go:S27')}${row('通報・問い合わせ','','go:S26')}${row('利用規約・プライバシー')}${row('アカウントの削除','','go:S28')}<p class="subtle" style="margin-top:24px">DECIDE v1.5 設計見本</p></div>`;
case'S24':return head('通知設定','S23')+`<div class="page"><div class="notice"><span>OSの通知許可：未確認（見本）</span></div>${toggle('友達の相談','新規・未回答はまとめてお届け',true)}${toggle('参加した相談の最終決断','決めたことを受け取る',true)}${toggle('自分の決断・振り返り','対応が必要なこと',true)}${toggle('DNAの更新','初期は通知しません')}${toggle('おやすみ時間','23:00〜08:00・Asia/Tokyo',true)}${toggle('私的な相談の内容をプレビュー','初期は質問・作者名を出しません')}${button('設定を保存','demo')}</div>`;
case'S25':return head('プロフィールの公開項目','S23')+`<div class="page"><p class="copy">見せたい項目だけ、公開できます。</p>${toggle('16タイプ')}${toggle('Decision DNA')}${toggle('友達数')}${toggle('フォロー数')}<div class="notice">${icon('lock')}<span>相談の公開範囲は、投稿ごとに選びます。</span></div><p class="subtle">他の人には、その人に共有した履歴の統計だけを表示します。</p>${button('設定を保存','demo')}</div>`;
case'S26':return head('通報・問い合わせ','S23')+`<div class="page"><h2 class="question">気になることを教えてください。</h2><label class="field">理由<select><option>個人情報・晒し</option><option>嫌がらせ・攻撃</option><option>危険な行為</option><option>その他</option></select></label>${field('補足（任意）','','',true,'最大300文字')}<p class="subtle">通報者の情報は、相手に伝わりません。</p>${button('通報内容を確認','demo')}${row('審査への異議申し立て','対象の案件から連絡できます')}</div>`;
case'S27':return head('ブロック管理','S23')+`<div class="page"><div class="empty"><div class="orb">${icon('lock',36)}</div><h2>ブロックした人は<br>いません</h2><p class="subtle">相手のプロフィールや投稿メニューからブロックできます。解除しても友達関係は自動で戻りません。</p></div></div>`;
case'S28':return head('アカウントの削除','S23')+`<div class="page"><h2 class="question">削除する前に。</h2><p class="copy">あなたの相談・投票・決断の記録が削除対象になります。共有した記録も見られなくなります。</p><div class="notice">${icon('lock')}<span>安全のため、もう一度本人確認を行います。</span></div>${button('本人確認へ進む','demo')}${button('削除しないで戻る','go:S23','secondary')}<p class="subtle" style="margin-top:18px">この見本では本人確認も削除も実行しません。</p></div>`;
case'W01':return detail(true);
case'W02':return head('この相談の続きも','W01')+`<div class="page">${summary()}<h2 class="question">ゆいが何に決めたか、知りたい？</h2><p class="copy">登録すると、参加した相談の最終決断を受け取れます。</p>${button('Appleで続ける','demo')}${button('Googleで続ける','demo','secondary')}${button('今はしない','go:W01','text-button')}<p class="subtle">登録後もゲストとして投じた票は匿名のままです。自動で友達にはなりません。</p></div>`;
case'W03':return head('DECIDE','S01')+`<div class="page"><div class="empty"><div class="orb">${icon('lock',36)}</div><h2>この相談は<br>表示できません</h2><p class="subtle">リンクを確認するか、送ってくれた人にお確かめください。</p>${button('ホームへ','go:S03','secondary')}</div></div>`;
case'A01':return head('審査キュー','S23')+`<div class="page"><p class="subtle">OPERATIONS · STAFF + MFA</p><div class="chips">${button('確認待ち 2','demo','selected')}${button('異議 1','demo','')}</div>${row('投稿内容の確認','高リスク候補・版3・8分待機','go:A02')}${row('ひとことの確認','版1・12分待機','go:A02')}<div class="notice"><span>通報件数だけでは削除しません。</span></div></div>`;
case'A02':return head('案件の確認','A01')+`<div class="page"><p class="subtle">対象版3・審査保留中</p><h2 class="question">投稿内容の確認</h2><div class="summary"><p class="copy">［架空の審査対象テキスト］</p><p class="subtle">実装時は権限付きで対象版の本文・画像・証拠を取得します。</p></div>${row('AI判定','高リスク候補。人の判断を代行しない')}${row('通報','3件。通報者は一般利用者へ非公開')}${field('判断理由','','',true,'監査に保存')}${button('公開を許可','demo')}${button('保留を維持','demo','secondary')}${button('違反として対応','demo','text-button')}</div>`;
default:throw Error('Unknown screen '+current);
}}
const overlays={O01:['写真の位置を調整',()=>'<img class="crop-image" src="assets/seoul.jpg" alt="位置調整の見本"><label class="field">左右の位置<input type="range" min="0" max="1" step="0.01" value="0.5"></label><p class="subtle">フィードでは正方形。元の写真は保持します。</p>'],O02:['期限を選ぶ',()=>'<div class="chips">'+['15分','1時間','3時間','1日','1週間','日時指定'].map(t=>button(t,'demo',t==='3時間'?'selected':'')).join('')+'</div>'+field('投票期限','2026-09-10 18:00')+field('決める目安','2026-09-11 23:59')],O03:['相談する友達',()=>field('名前で検索')+toggle('ゆい','@yui',true)+toggle('あおい','@aoi')+'<p class="subtle">選択：1人。匿名相談では全員が対象です。</p>'],O04:['ひとこと添える',()=>field('この二択について','','',true,'任意80文字・1人1件')+'<p class="subtle">投票終了後に表示されます。返信・いいねはありません。</p>'],O05:['相談のメニュー',()=>row('補足を追記する','初票後は元の内容を編集できません','sheet:O04')+row('カテゴリを修正','','sheet:O09')+row('回答者を見る','','sheet:O06')+row('通報する','','go:S26')],O06:['回答者',()=>'<p class="subtle">記名・投票終了後の例。公開投稿ではこの一覧を表示しません。</p>'+row('A 韓国','登録票：ゆい')+row('B 台湾','登録票：あおい')+'<p class="subtle">ゲスト票：2。個別の名前は表示しません。</p>'],O07:['選択を変更しますか？',()=>'<p class="copy">変更すると、この投票は確定します。もう一度変更することはできません。</p>'+button('選択を変更して確定','change')],O08:['投票を終了しますか？',()=>'<p class="copy">新しい投票を締め切り、集計を見てあなたの決断を記録できます。終了後は再開できません。</p>'+button('終了して決断する','close-poll')],O09:['カテゴリを修正',()=>'<div class="chips">'+['恋愛','人間関係','ファッション・美容','食事','買い物','旅行・おでかけ','学校・仕事','趣味・エンタメ','お金・経済','政治・社会','その他'].map(t=>button(t,'demo','')).join('')+'</div>'],O10:['まだ結果が分からない',()=>'<p class="copy">振り返りの通知を、1回だけ延期できます。</p>'+button('7日後に知らせる','postpone')+button('日時を選ぶ','demo','secondary')+'<p class="subtle">元の通知は取り消され、延期先で1回だけお知らせします。</p>']};
function palette(){const c=window.DECIDE_TOKENS.colors[$('#theme-select').value];for(const el of [$('#phone'),$('#sheet')])for(const [k,v]of Object.entries(c))el.style.setProperty('--'+k,v)}
function render(){palette();const width=Number($('#width-select').value),scale=Number($('#scale-select').value);$('#phone').style.width=width+'px';$('#phone').style.setProperty('--scale',scale);$('#phone').classList.toggle('narrow',width<350);$('#phone').classList.toggle('scaled',scale>=1.5);$('#app').innerHTML=screenContent();$('#screen-select').value=current;const s=screens.find(s=>s.id===current);$('#annotation').innerHTML=`<h3>${s.id} ${esc(s.name)}</h3><code>${esc(s.route)}</code><p>${esc(s.content)}</p><p>${esc(s.rules)}</p>`;$('#caption').textContent=s.id+' / '+s.name+' · DECIDE v1.5';document.documentElement.dataset.screen=current;}
function go(id){closeSheet();current=id;state='default';$('#state-select').value='default';if(['S03','S04','S08','W01'].includes(id)){selected=null;locked=false}if(id==='S09'){selected='A';locked=false}render()}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function openSheet(id){if(!overlays[id])return;lastFocus=document.activeElement;$('#overlay-select').value=id;$('#sheet-body').innerHTML=`<div class="sheet-head"><h2 id="sheet-title">${overlays[id][0]}</h2>${ib('close','閉じる','close-sheet')}</div>`+overlays[id][1]()+(!['O07','O08','O10'].includes(id)?button('見本を閉じる','close-sheet','secondary'):'');palette();if(!$('#sheet').open)$('#sheet').showModal()}
function closeSheet(){if($('#sheet').open)$('#sheet').close();$('#overlay-select').value='';if(lastFocus?.isConnected)lastFocus.focus();lastFocus=null}
$('#screen-select').innerHTML=screens.map(s=>`<option value="${s.id}">${s.id} ${s.name}</option>`).join('');$('#screen-select').addEventListener('change',e=>go(e.target.value));$('#state-select').addEventListener('change',e=>{state=e.target.value;render()});for(const s of ['#theme-select','#width-select','#scale-select'])$(s).addEventListener('change',render);$('#overlay-select').addEventListener('change',e=>e.target.value?openSheet(e.target.value):closeSheet());$('#sheet').addEventListener('cancel',()=>$('#overlay-select').value='');
document.addEventListener('input',e=>{if(e.target.dataset.draft)draft[e.target.dataset.draft]=e.target.value});
document.addEventListener('click',e=>{const target=e.target.closest('[data-a]');if(!target)return;const a=target.dataset.a;
if(a.startsWith('go:'))return go(a.slice(3));if(a.startsWith('sheet:'))return openSheet(a.slice(6));if(a==='close-sheet')return closeSheet();
if(a.startsWith('vote:')){if(locked)return toast('確定済みです。');selected=a.slice(5);if(current!=='W01')current='S09';render();return;}
if(a==='lock'){locked=true;render();return}if(a==='change'){selected=selected==='A'?'B':'A';locked=true;closeSheet();render();return}
if(a.startsWith('score:')){score=Number(a.slice(6));render();return}if(a.startsWith('final:')){finalChoice=a.slice(6);render();return}
if(a==='save-review'){go('S17');toast('選んだ点数を見本へ反映しました。サーバーには保存していません。');return}
if(a==='save-final'){recordedFinal=finalChoice;go('S17');toast('決断画面の遷移見本です。実記録は作成しません。');return}
if(a==='close-poll'){go('S10');return}if(a==='settings'){advanced=!advanced;render();return}if(a.startsWith('audience:')){audience=a.slice(9);render();return}if(a.startsWith('notify:')){notify=a.slice(7);render();return}
if(a==='retry'){state='default';$('#state-select').value='default';render();return}
if(a==='next-compose'){const seg=new Intl.Segmenter('ja',{granularity:'grapheme'});for(const [k,max]of [['question',80],['A',30],['B',30],['context',300]]){const v=draft[k].normalize('NFC').trim();if((k!=='context'&&!v)||[...seg.segment(v)].length>max){$('#input-error').textContent='必須項目と文字数を確認してください。';return}}if(draft.A.trim()===draft.B.trim()){$('#input-error').textContent='AとBは異なる選択肢にしてください。';return}go('S06');return}
if(a.startsWith('image:')){lastFocus=target;$('#sheet-body').innerHTML=`<div class="sheet-head"><h2 id="sheet-title">写真</h2>${ib('close','閉じる','close-sheet')}</div><img style="width:100%;border-radius:16px" src="assets/${a.endsWith('A')?'seoul':'taipei'}.jpg" alt="写真の拡大">`;palette();$('#sheet').showModal();return}
if(a==='postpone'){closeSheet();toast('延期の見本：操作から7日後に1回。サーバーの通知は変更していません。');return}
if(a==='defer')return toast('保留の見本。最終決断やReviewは作りません。');if(a==='dismiss')return toast('催促終了の見本。後から振り返れます。');
toast('設計見本です。送信・保存・外部への操作は行いません。');
});
window.DECIDE_CATALOG={go,render,openSheet,closeSheet};render();
